### ISSUE TITLE
Script just not function (no errors)

### ISSUE THREAD

**Issue by Stnadageah** [Xorzo-Scripts/xz-shoplift#1]
Script not function, its starting, all requirements installed and no errors

![image](https://user-images.githubusercontent.com/100540979/161425355-824dced4-8dff-4d6d-a16a-45917a1a6664.png)

**Comment by xorzo1** [comment]
Good Afternoon @Stnadageah,

Do you have any more information,

Dubble check if you have all dependencies installed:
-Qtarget
-Polyzone

Are there also no errors when executing the action? I tested it myself and everything works just fine.

Make sure your database is setup the right way "esx_legacy"

Kind regards,
xorzo.

**Comment by xorzo1** [comment]
We found out that there's an issue with the script. we are investigating.

**Comment by xorzo1** [comment]
@Stnadageah,
Download the latest version and your issue should be resolved. ❤️
